TRUNCATE vehicles_categories CASCADE;
TRUNCATE models_model_years CASCADE;

TRUNCATE vehicles RESTART IDENTITY CASCADE;
TRUNCATE categories RESTART IDENTITY CASCADE;
TRUNCATE models RESTART IDENTITY CASCADE;
TRUNCATE model_years RESTART IDENTITY CASCADE;
TRUNCATE makes RESTART IDENTITY CASCADE;
