-- Vehicle.categories
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(1, 1);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(2, 2);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(3, 1);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(4, 3), (4, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(5, 2);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(6, 4);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(7, 2), (7, 8);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(8, 4);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(9, 5), (9, 2), (9, 3);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(10, 5);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(11, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(12, 1);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(13, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(14, 6), (14, 2);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(15, 2), (15, 3), (15, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(16, 1);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(17, 3), (17, 2), (17, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(18, 2);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(19, 3);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(20, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(21, 7);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(22, 7);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(23, 1);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(24, 2);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(25, 3), (25, 6), (25, 2), (25, 8);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(26, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(27, 8);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(28, 5);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(29, 5);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(30, 2), (30, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(31, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(32, 8);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(33, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(34, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(35, 3);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(36, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(37, 1);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(38, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(39, 2), (39, 6), (39, 3);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(40, 3), (40, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(41, 8);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(42, 8), (42, 2);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(43, 6), (43, 2), (43, 3);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(44, 2), (44, 6), (44, 3);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(45, 8);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(46, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(47, 8);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(48, 3), (48, 6), (48, 2), (48, 8);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(49, 2), (49, 6), (49, 8);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(50, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(51, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(52, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(53, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(54, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(55, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(56, 1), (56, 4);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(57, 3), (57, 2), (57, 6), (57, 8);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(58, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(59, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(60, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(61, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(62, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(63, 5);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(64, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(65, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(66, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(67, 2), (67, 3), (67, 8), (67, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(68, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(69, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(70, 5);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(71, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(72, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(73, 5);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(74, 6);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(75, 1);
INSERT INTO public."vehicles_categories" (vehicle_id, category_id) VALUES(76, 6);
