-- VehicleModel
ALTER SEQUENCE IF EXISTS "models_id_seq" RESTART WITH 1;
INSERT INTO public."models" (id, name, make_id) VALUES(1, 'Q3', 1);
INSERT INTO public."models" (id, name, make_id) VALUES(2, 'Malibu', 2);
INSERT INTO public."models" (id, name, make_id) VALUES(3, 'Escalade ESV', 3);
INSERT INTO public."models" (id, name, make_id) VALUES(4, 'Corvette', 2);
INSERT INTO public."models" (id, name, make_id) VALUES(5, 'RLX', 4);
INSERT INTO public."models" (id, name, make_id) VALUES(6, 'Silverado 2500 HD Crew Cab', 2);
INSERT INTO public."models" (id, name, make_id) VALUES(7, '3 Series', 5);
INSERT INTO public."models" (id, name, make_id) VALUES(8, 'Sierra 2500 HD Crew Cab', 6);
INSERT INTO public."models" (id, name, make_id) VALUES(9, 'Civic', 7);
INSERT INTO public."models" (id, name, make_id) VALUES(10, 'Elantra GT', 8);
INSERT INTO public."models" (id, name, make_id) VALUES(11, 'F-TYPE', 9);
INSERT INTO public."models" (id, name, make_id) VALUES(12, 'NX', 10);
INSERT INTO public."models" (id, name, make_id) VALUES(13, '911', 11);
INSERT INTO public."models" (id, name, make_id) VALUES(14, 'A3', 1);
INSERT INTO public."models" (id, name, make_id) VALUES(15, 'S5', 1);
INSERT INTO public."models" (id, name, make_id) VALUES(16, 'e-tron', 1);
INSERT INTO public."models" (id, name, make_id) VALUES(17, 'A5', 1);
INSERT INTO public."models" (id, name, make_id) VALUES(18, 'M6', 5);
INSERT INTO public."models" (id, name, make_id) VALUES(19, 'Z4', 5);
INSERT INTO public."models" (id, name, make_id) VALUES(20, 'Express 2500 Cargo', 2);
INSERT INTO public."models" (id, name, make_id) VALUES(21, 'Transit 150 Wagon', 13);
INSERT INTO public."models" (id, name, make_id) VALUES(22, 'Continental', 14);
INSERT INTO public."models" (id, name, make_id) VALUES(23, 'Mercedes-AMG E-Class', 15);
INSERT INTO public."models" (id, name, make_id) VALUES(24, '718 Boxster', 11);
INSERT INTO public."models" (id, name, make_id) VALUES(25, 'Golf SportWagen', 16);
INSERT INTO public."models" (id, name, make_id) VALUES(26, 'e-Golf', 16);
INSERT INTO public."models" (id, name, make_id) VALUES(27, 'Golf', 16);
INSERT INTO public."models" (id, name, make_id) VALUES(28, 'Continental', 17);
INSERT INTO public."models" (id, name, make_id) VALUES(29, 'V60', 12);
INSERT INTO public."models" (id, name, make_id) VALUES(30, 'California', 18);
INSERT INTO public."models" (id, name, make_id) VALUES(31, '488 Spider', 18);
INSERT INTO public."models" (id, name, make_id) VALUES(32, 'Q60', 19);
INSERT INTO public."models" (id, name, make_id) VALUES(33, 'Dawn', 20);
INSERT INTO public."models" (id, name, make_id) VALUES(34, 'Boxster', 11);
INSERT INTO public."models" (id, name, make_id) VALUES(35, 'Phantom', 20);
INSERT INTO public."models" (id, name, make_id) VALUES(36, 'Venza', 21);
INSERT INTO public."models" (id, name, make_id) VALUES(37, 'Outback', 22);
INSERT INTO public."models" (id, name, make_id) VALUES(38, 'E-Class', 15);
INSERT INTO public."models" (id, name, make_id) VALUES(39, '45538', 23);
INSERT INTO public."models" (id, name, make_id) VALUES(40, 'Azure T', 17);
INSERT INTO public."models" (id, name, make_id) VALUES(41, 'SC', 10);
INSERT INTO public."models" (id, name, make_id) VALUES(42, 'S4', 1);
INSERT INTO public."models" (id, name, make_id) VALUES(43, 'Azure', 17);
INSERT INTO public."models" (id, name, make_id) VALUES(44, 'S2000', 7);
INSERT INTO public."models" (id, name, make_id) VALUES(45, 'SLR McLaren', 15);
INSERT INTO public."models" (id, name, make_id) VALUES(46, 'H2', 25);
INSERT INTO public."models" (id, name, make_id) VALUES(47, 'Carrera GT', 11);
INSERT INTO public."models" (id, name, make_id) VALUES(48, 'Thunderbird', 13);
INSERT INTO public."models" (id, name, make_id) VALUES(49, 'Z8', 5);
INSERT INTO public."models" (id, name, make_id) VALUES(50, 'Golf (New)', 16);
INSERT INTO public."models" (id, name, make_id) VALUES(51, 'Cabriolet', 1);
INSERT INTO public."models" (id, name, make_id) VALUES(52, 'Z3', 5);
INSERT INTO public."models" (id, name, make_id) VALUES(53, 'Cavalier', 2);
INSERT INTO public."models" (id, name, make_id) VALUES(54, '500 SL', 15);
INSERT INTO public."models" (id, name, make_id) VALUES(55, '600 SL', 15);
INSERT INTO public."models" (id, name, make_id) VALUES(56, 'NX', 26);
INSERT INTO public."models" (id, name, make_id) VALUES(57, 'Cabriolet', 16);
INSERT INTO public."models" (id, name, make_id) VALUES(58, '300 SL', 15);
INSERT INTO public."models" (id, name, make_id) VALUES(59, '718 Spyder', 11);

ALTER SEQUENCE IF EXISTS "models_id_seq" RESTART WITH 101;
